### ISSUE TITLE
Layer changes for intangibles

### ISSUE THREAD

**Issue by knoxd8256** [MLH-Fellowship/red-panda#5]
Right now I have added logic to directly ignore a few classes of objects (safe and fear zones in particular) when detecting ground and platforms, but simply moving them to the "Ignore Raycasts" layer should fix this and result in a cleaner implementation. This is low priority but would be a good step towards the "clean code" theme of this sprint.

**Comment by skymake** [comment]
Added ignore raycasts to intangibles and updated prefabs accordingly.
